import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;
import 'package:logger/logger.dart';

final _r2Log = Logger();

/// Service to obtain a pre-signed PUT URL (generated by a Cloudflare Worker or Firebase Function)
/// then upload a binary object (audio / pdf / doc / zip ... ) to Cloudflare R2.
/// Expected backend endpoint response JSON:
/// { "putUrl": "https://...presigned...", "publicUrl": "https://cdn/..." }
class R2UploadService {
  final String
  presignEndpoint; // e.g. https://your-worker.example.workers.dev/presign?ext=
  R2UploadService({required this.presignEndpoint});

  /// Generic object upload. Detects / uses provided contentType.
  Future<String> uploadObject(
    File file, {
    required String extension,
    required String contentType,
  }) async {
    // Allow placeholder pattern {ext} OR trailing ?ext=
    String resolvedEndpoint;
    if (presignEndpoint.contains('{ext}')) {
      resolvedEndpoint = presignEndpoint.replaceAll('{ext}', extension);
    } else {
      // تأكد ألا نكرر الامتداد لو المستخدم كتب m4a مسبقاً
      resolvedEndpoint = presignEndpoint.endsWith('=')
          ? '$presignEndpoint$extension'
          : '$presignEndpoint$extension';
    }
    _r2Log.i('[R2] Requesting presign from: $resolvedEndpoint');
    http.Response presignResp;
    try {
      presignResp = await http
          .get(Uri.parse(resolvedEndpoint))
          .timeout(const Duration(seconds: 10));
    } on Exception catch (e) {
      throw Exception('Presign request failed (network/timeout): $e');
    }
    if (presignResp.statusCode != 200) {
      final bodySnippet = presignResp.body.replaceAll('\n', ' ').trim();
      // حاول استخراج كود خطأ Cloudflare إن وجد
      final cfMatch = RegExp(
        r'cf-error-code"?>\s*(\\n)?(\d{3,4})',
      ).firstMatch(presignResp.body);
      final cfCode = cfMatch?.group(2);
      throw Exception(
        'Presign endpoint failed (status=${presignResp.statusCode}${cfCode != null ? ', cf=$cfCode' : ''}) snippet="${bodySnippet.substring(0, bodySnippet.length.clamp(0, 240))}"',
      );
    }
    Map<String, dynamic> data;
    try {
      if (!(presignResp.headers['content-type'] ?? '').toLowerCase().contains(
        'application/json',
      )) {
        throw Exception(
          'Unexpected content-type: ${presignResp.headers['content-type']}',
        );
      }
      data = jsonDecode(presignResp.body) as Map<String, dynamic>;
    } catch (e) {
      throw Exception(
        'Failed to parse presign JSON: $e | body="${presignResp.body.substring(0, presignResp.body.length.clamp(0, 240))}"',
      );
    }
    final putUrl = data['putUrl'] as String?;
    final publicUrl = data['publicUrl'] as String?;
    if (putUrl == null || publicUrl == null) {
      throw Exception('Invalid presign response keys: $data');
    }
    final bytes = await file.readAsBytes();
    http.Response putResp;
    try {
      putResp = await http
          .put(
            Uri.parse(putUrl),
            headers: {'Content-Type': contentType},
            body: bytes,
          )
          .timeout(const Duration(seconds: 30));
    } on Exception catch (e) {
      throw Exception('PUT upload failed (network/timeout): $e');
    }
    if (putResp.statusCode != 200 && putResp.statusCode != 201) {
      _r2Log.e(
        '[R2] Upload failed status=${putResp.statusCode} body=${putResp.body.substring(0, putResp.body.length.clamp(0, 240))}',
      );
      throw Exception('R2 upload failed (status=${putResp.statusCode})');
    }
    _r2Log.i('[R2] Upload success -> $publicUrl');
    return publicUrl;
  }

  /// Backward-compatible helper for audio (still used in some places)
  Future<String> uploadAudio(File file, {String extension = 'm4a'}) {
    return uploadObject(
      file,
      extension: extension,
      contentType: 'audio/$extension',
    );
  }
}
