import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;
import 'package:logger/logger.dart';

final _spacesLog = Logger();

/// Service to obtain a pre-signed PUT URL (generated by your backend)
/// and upload an object to DigitalOcean Spaces (S3-compatible).
/// Expected JSON structure (angle brackets removed to avoid HTML parsing):
/// { "putUrl": "https://SPACE.REGION.digitaloceanspaces.com/obj?...", "publicUrl": "https://cdn.example.com/obj" }
class SpacesUploadService {
  final String
  presignEndpoint; // e.g. https://api.example.com/spaces/presign?ext=
  SpacesUploadService({required this.presignEndpoint});

  Future<String> uploadObject(
    File file, {
    required String extension,
    required String contentType,
  }) async {
    // 1. Build presign endpoint (supports pattern with {ext} or simple suffix)
    final endpoint = presignEndpoint.contains('{ext}')
        ? presignEndpoint.replaceAll('{ext}', extension)
        : (presignEndpoint.endsWith('=')
              ? '$presignEndpoint$extension'
              : '$presignEndpoint$extension');

    // 2. Request presigned data
    _spacesLog.i(
      '[Spaces] Presign -> $endpoint (ext=$extension ct=$contentType)',
    );
    http.Response presign;
    final presignStart = DateTime.now();
    try {
      presign = await http
          .get(Uri.parse(endpoint))
          .timeout(const Duration(seconds: 10));
    } catch (e) {
      throw Exception('Spaces presign failed: $e');
    }
    final presignMs = DateTime.now().difference(presignStart).inMilliseconds;
    if (presign.statusCode != 200) {
      throw Exception(
        'Spaces presign status=${presign.statusCode} bodySnippet="${presign.body.substring(0, presign.body.length.clamp(0, 200))}"',
      );
    }

    // 3. Decode JSON
    Map<String, dynamic> data;
    try {
      data = jsonDecode(presign.body) as Map<String, dynamic>;
    } catch (e) {
      throw Exception('Spaces presign JSON parse error: $e');
    }
    final putUrl = data['putUrl'] as String?;
    final publicUrl = data['publicUrl'] as String?;
    // Worker may return an explicit contentType and/or acl it used when signing.
    final workerContentType = (data['contentType'] as String?)?.trim();
    if (putUrl == null || publicUrl == null) {
      throw Exception('Invalid presign keys: $data');
    }

    final putUri = Uri.parse(putUrl);
    final signedHeadersParam =
        putUri.queryParameters['X-Amz-SignedHeaders'] ??
        putUri.queryParameters['x-amz-signedheaders'];
    final signedHeaders =
        signedHeadersParam
            ?.split(';')
            .map((e) => e.trim().toLowerCase())
            .where((e) => e.isNotEmpty)
            .toList() ??
        const <String>[];

    // 4. Read file bytes & sanity checks
    if (!await file.exists()) {
      throw Exception('Audio file not found at ${file.path}');
    }
    final fileLength = await file.length();
    if (fileLength == 0) {
      throw Exception('Audio file is empty (0 bytes) path=${file.path}');
    }
    // Sometimes recorder closes a fraction later; if extremely small, wait & re-measure once.
    if (fileLength < 1024) {
      await Future.delayed(const Duration(milliseconds: 120));
    }
    final bytes = await file.readAsBytes();

    // 5. Build headers only with those that appear in signed headers (avoid mismatch if worker included content-type in signature).
    final Map<String, String> uploadHeaders = {};
    final effectiveContentType =
        (workerContentType != null && workerContentType.isNotEmpty)
        ? workerContentType
        : contentType;
    final needContentType =
        signedHeaders.contains('content-type') ||
        signedHeaders.isEmpty; // allow when not constrained.
    if (needContentType) {
      uploadHeaders['Content-Type'] = effectiveContentType;
    }
    // Force public-read so trainee can access audio (host-only signature allows extra headers safely)
    uploadHeaders['x-amz-acl'] = 'public-read';

    _spacesLog.i(
      '[Spaces] PUT start host=${putUri.host} path=${putUri.path} size=${bytes.length}B signedHeaders=${signedHeaders.join(',')} ct=$effectiveContentType acl=${uploadHeaders['x-amz-acl']} Presign ${presignMs}ms',
    );

    Future<http.Response> doPut({
      required bool omitContentType,
      bool stripAllOptional = false,
    }) async {
      Map<String, String> hdrs = Map<String, String>.from(uploadHeaders);
      if (stripAllOptional) {
        // Remove headers that are not strictly required; keep only those explicitly in signedHeaders.
        hdrs.removeWhere((k, v) => !signedHeaders.contains(k.toLowerCase()));
      } else if (omitContentType) {
        hdrs.remove('Content-Type');
      }
      _spacesLog.d(
        '[Spaces] Attempt PUT headers=${hdrs.entries.map((e) => '${e.key}:${e.value}').join(';')}',
      );
      return http
          .put(putUri, headers: hdrs, body: bytes)
          .timeout(const Duration(seconds: 30));
    }

    http.Response putResp;
    try {
      putResp = await doPut(omitContentType: false);
    } catch (e) {
      throw Exception('Spaces upload network error: $e');
    }

    // 6. Retry logic for 403/400 with alternate header strategy (some signatures reject content-type header if not signed)
    if (putResp.statusCode == 403 || putResp.statusCode == 400) {
      final bodySnippet = putResp.body.substring(
        0,
        putResp.body.length.clamp(0, 180),
      );
      _spacesLog.w(
        '[Spaces] First PUT failed (${putResp.statusCode}) retrying without Content-Type (snippet="$bodySnippet")',
      );
      try {
        final retryResp = await doPut(omitContentType: true);
        if (retryResp.statusCode == 200 || retryResp.statusCode == 201) {
          _spacesLog.i(
            '[Spaces] Upload success (retry w/o Content-Type) -> $publicUrl',
          );
          return publicUrl;
        } else {
          _spacesLog.w(
            '[Spaces] Retry (no Content-Type) failed status=${retryResp.statusCode}',
          );
          // Third attempt: strip all optional headers (e.g., x-amz-acl) to detect if ACL causes rejection.
          if (retryResp.statusCode == 403) {
            _spacesLog.w(
              '[Spaces] Trying third attempt stripping optional headers',
            );
            final third = await doPut(
              omitContentType: true,
              stripAllOptional: true,
            );
            if (third.statusCode == 200 || third.statusCode == 201) {
              _spacesLog.i(
                '[Spaces] Upload success (third attempt minimal headers) -> $publicUrl',
              );
              return publicUrl;
            }
            _spacesLog.e(
              '[Spaces] Third attempt failed status=${third.statusCode} body=${third.body.substring(0, third.body.length.clamp(0, 200))}',
            );
            throw Exception(
              'Spaces upload failed status=${third.statusCode} (after third attempt)',
            );
          }
          _spacesLog.e(
            '[Spaces] Retry failed status=${retryResp.statusCode} body=${retryResp.body.substring(0, retryResp.body.length.clamp(0, 200))}',
          );
          throw Exception(
            'Spaces upload failed status=${retryResp.statusCode} (after retry)',
          );
        }
      } catch (e) {
        rethrow;
      }
    }

    if (putResp.statusCode != 200 && putResp.statusCode != 201) {
      _spacesLog.e(
        '[Spaces] Upload failed status=${putResp.statusCode} body=${putResp.body.substring(0, putResp.body.length.clamp(0, 200))} headersUsed=${uploadHeaders.keys.join(',')} signedHeaders=${signedHeaders.join(',')}',
      );
      throw Exception('Spaces upload failed status=${putResp.statusCode}');
    }

    _spacesLog.i('[Spaces] Upload success -> $publicUrl');
    return publicUrl;
  }

  /// Upload an audio file (default recorded extension m4a) with a correct, widely
  /// supported MIME type. Note: .m4a should normally use `audio/mp4` not
  /// `audio/m4a` (some players reject the non-standard type). We map the most
  /// common extensions; anything unknown falls back to `application/octet-stream`.
  Future<String> uploadAudio(File file, {String extension = 'm4a'}) {
    final ct = _mimeForAudio(extension.toLowerCase());
    return uploadObject(file, extension: extension, contentType: ct);
  }

  String _mimeForAudio(String ext) {
    switch (ext) {
      case 'm4a':
      case 'mp4':
        return 'audio/mp4';
      case 'aac':
        return 'audio/aac';
      case 'mp3':
        return 'audio/mpeg';
      case 'wav':
        return 'audio/wav';
      case 'ogg':
        return 'audio/ogg';
      default:
        return 'application/octet-stream';
    }
  }
}
