// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqKFUGDU6QI42OXuzuuKZ1WcOObT7c3o8',
    appId: '1:564201926492:web:ce9462fd63a43853175b99',
    messagingSenderId: '564201926492',
    projectId: 'trainingapp-mvp',
    authDomain: 'trainingapp-mvp.firebaseapp.com',
    storageBucket: 'trainingapp-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3GAqXRfsz1DCCGzLDpNAV1dxWbJw4YEU',
    appId: '1:564201926492:android:7d2d209e8661b460175b99',
    messagingSenderId: '564201926492',
    projectId: 'trainingapp-mvp',
    storageBucket: 'trainingapp-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4-AVgspRApaxpboYvWVjf-dugNGQwdjo',
    appId: '1:564201926492:ios:dd1c3cd3bd0c4743175b99',
    messagingSenderId: '564201926492',
    projectId: 'trainingapp-mvp',
    storageBucket: 'trainingapp-mvp.firebasestorage.app',
    iosBundleId: 'com.example.trainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4-AVgspRApaxpboYvWVjf-dugNGQwdjo',
    appId: '1:564201926492:ios:dd1c3cd3bd0c4743175b99',
    messagingSenderId: '564201926492',
    projectId: 'trainingapp-mvp',
    storageBucket: 'trainingapp-mvp.firebasestorage.app',
    iosBundleId: 'com.example.trainingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqKFUGDU6QI42OXuzuuKZ1WcOObT7c3o8',
    appId: '1:564201926492:web:3d282324a33ce4d6175b99',
    messagingSenderId: '564201926492',
    projectId: 'trainingapp-mvp',
    authDomain: 'trainingapp-mvp.firebaseapp.com',
    storageBucket: 'trainingapp-mvp.firebasestorage.app',
  );
}
